#define CPU_FILE_NOT_FOUND 10
#define WHOAMI_CMD_FAILED 11
#define USERNAME_TOO_LONG 12
#define RAM_DATA_TOO_LONG 13
#define FREE_COMMAND_NOT_FOUND 14
#define PS_CMD_NOT_FOUND 15
#define OUT_OF_MEMORY 16
#define NON_LINUX_OS 17